apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: bookinfo-subscription
  namespace: bookinfo-helmrepo
  labels:
    app: bookinfo-helmrepo
    purpose: bookinfo-helmrepo-demo
spec:
  channel: bookinfo-helmrepo/bookinfo-helmrepo
  packageFilter:
    version: 1.0.7
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-placementrule
  overrides:
  - clusterName: "/"
    clusterOverrides:
    - path: "metadata.namespace"
      value: bookinfo
  packageOverrides:
  - packageName: bookinfo
    packageOverrides:
    - path: spec.releaseName
      value: bookinfo-demo
    - path: spec.values
      value: |
        ingress:
          host: bookinfo.apps.blue-12.dev.multicloudops.io