---
apiVersion: batch/v1
kind: Job
metadata:
  name: open-cluster-management-e2e-tests-job
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 360
  template:
    spec:
      containers:
      - name: open-cluster-management-e2e
        image: open-cluster-management-e2e:1.0.0
        env:
        - name: KUBE_USER
          valueFrom:
            secretKeyRef:
              name: e2e-job
              key: KUBE_USER
        - name: KUBE_USER_CREDENTIAL
          valueFrom:
            secretKeyRef:
              name: e2e-job
              key: KUBE_USER_CREDENTIAL
        - name: BASE_DOMAIN
          valueFrom:
            secretKeyRef:
              name: e2e-job
              key: BASE_DOMAIN
        volumeMounts:
          - name: e2e-job-results
            mountPath: /results
      volumes:
        - name: e2e-job-results
          persistentVolumeClaim:
            claimName: e2e-job-results-claim
      restartPolicy: Never