apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: dev-placementrule
  namespace: bookinfo-github
  labels:
    purpose: bookinfo-github-demo
spec:
  clusterConditions:
    - type: OK
  clusterSelector:
    matchExpressions: []
    matchLabels:
      environment: Dev