---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: guestbook-app-latest
  namespace: guestbook-app
spec:
  type: GitHub
  pathname: https://github.com/kubernetes/examples.git
  # secretRef:
  #   name: github-credentials
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: guestbook-app
  namespace: guestbook-app
  labels:
    app: guestbook-app
spec:
  channel: guestbook-app/guestbook-app-latest
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-clusters
  packageFilter:
    filterRef:
      name: resource-filter-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-filter-configmap
  namespace: guestbook-app
  labels:
    app: guestbook-app
data:
    path: examples/guestbook