apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: "<CLUSTER_NAME>"

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: install-config
  type: "Opaque"
  files:
    - "install-config.yaml"
- name: ssh-privatekey
  type: "Opaque"
  files:
    - "ssh-privatekey"
- name: aws-creds
  type: "Opaque"
  literals:
    - aws_access_key_id=<AWS_ACCESS_KEY>
    - aws_secret_access_key=<AWS_SECRET_ACCESS_KEY>
- name: openshift-installer-pull-secret
  type: "kubernetes.io/dockerconfigjson"
  literals:
    - .dockerconfigjson='<OCP_PULL_SECRET>'

resources:
  - namespace.yaml
  - machine-pool.yaml
  - imageset.yaml
  - endpoint-config.yaml
  - cluster-deployment.yaml
  - cluster.yaml