blank_issues_enabled: false
contact_links:
  - name: Open Cluster Management Community Forum
    url: https://coreos.slack.com/archives/CTDEY6EEA
    about: You can find us on the CoreOS Slack Channel [#forum-acm](https://coreos.slack.com/archives/CTDEY6EEA). Please ask your questions there.