apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: bookinfo
  namespace: bookinfo
spec:
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - bookinfo
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription