apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  annotations:
    "mch-imageRepository": "quay.io/open-cluster-management"
spec:
  imagePullSecret: multiclusterhub-operator-pull-secret
  