# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: open-cluster-management

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: multiclusterhub-operator-index
    newName: quay.io/open-cluster-management/multiclusterhub-operator-index
    newTag: 1.0.0-SNAPSHOT-2020-03-18-02-33-16

# list of Resource Config to be Applied
resources:
  - deployment.yaml
  - service.yaml
  - catalog-source.yaml
  - operator-group.yaml
  - subscription.yaml