apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: "spoke"

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: install-config
  type: "Opaque"
  files:
    - "install-config.yaml"
- name: ssh-privatekey
  type: "Opaque"
  files:
    - "ssh-privatekey"
- name: aws-creds
  type: "Opaque"
  literals:
    - aws_access_key_id=
    - aws_secret_access_key=
- name: openshift-installer-pull-secret
  type: "kubernetes.io/dockerconfigjson"
  literals:
    - .dockerconfigjson=''

resources:
  # - namespace.yaml
  - machine-pool.yaml
  - imageset.yaml
  - endpoint-config.yaml
  - cluster-deployment.yaml
  - cluster.yaml