---
apiVersion: v1
kind: ConfigMap
metadata:
  name: policies-path
  namespace: open-cluster-management
data:
    # path: policies
    path: artifacts/policies-acm
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: policies
  namespace: open-cluster-management
spec:
  channel: open-cluster-management/policies
  placement:
    local: true
  packageFilter:
    filterRef:
      name: policies-path